export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export LSCOLORS=ExFxBxDxCxegedabagacad

# For OS X : -G, for Ubuntu --color=auto
alias ls='ls -GF'
alias ll='ls -lAthGF'
alias la='ls -AGF'

alias u='cd ..'
alias grep='grep --color=auto'
